### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by danilopolani** [adonisjs/adonis-antl#31] opened 2018-05-07 14:38 UTC
Hi guys,
is it possible to add support for nested properties, for example `cities.city.new_york`?

```
cities.json

{
  "city": {
    "new_york": "New York"
  }
}
```

Since it depends on `intl-messageformat`, this could be a nice hint: https://github.com/yahoo/intl-messageformat/issues/113#issuecomment-162675406

**Comment by thetutlage** [comment] 2018-05-08 03:49
Duplicate of https://github.com/adonisjs/adonis-antl/issues/32#issuecomment-387275931

**Closed by thetutlage** 2018-05-08 03:49 UTC
